### ISSUE TITLE
Is this live?

### ISSUE THREAD

**Issue by ManiacMinor** [Dom-in/ASF-Bot#9]
Hello, I followed the instructions but keep getting an error.

Is this still in dev?

If not what are the requirements?

Thanks

**Comment by zerox003** [comment]
What is your error?

**Comment by ManiacMinor** [comment]
Looks like I was missing Privileged Gateway Intents on the Dev Portal.
After giving these, the Bot activates but cannot speak with ASF.

It is constantly getting fetch errors.
That is the correct IP & Port.

Going to [https://127.0.0.1:1242/Api/Bot/ASF](https://127.0.0.1:1242/Api/Bot/ASF) directly gives
"An error occurred during a connection to 127.0.0.1:1242. SSL received a record that exceeded the maximum permissible length."

Below is the cmd:
```cmd
C:\Users\Brooklin\Documents\GitHub\ASF-Bot>node run.js
Executing regcmd.js...
Running file: regcmd.js
Error from regcmd.js: (node:4532) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
Error from regcmd.js: Fetch error: FetchError: request to https://127.0.0.1:1242/Api/Bot/ASF failed, reason: write EPROTO D81B0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:c:\ws\deps\openssl\openssl\ssl\record\ssl3_record.c:355:

    at ClientRequest.<anonymous> (C:\Users\Brooklin\Documents\GitHub\ASF-Bot\node_modules\node-fetch\lib\index.js:1491:11)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'EPROTO',
  code: 'EPROTO'
}
Output from regcmd.js: Started refreshing application (/) commands. (This might take a bit)
Output from regcmd.js: Successfully deleted all commands.
Output from regcmd.js: Successfully reloaded application (/) commands.
regcmd.js exited with code 0
Warnings occurred while running regcmd.js:
(node:4532) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
Fetch error: FetchError: request to https://127.0.0.1:1242/Api/Bot/ASF failed, reason: write EPROTO D81B0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:c:\ws\deps\openssl\openssl\ssl\record\ssl3_record.c:355:

    at ClientRequest.<anonymous> (C:\Users\Brooklin\Documents\GitHub\ASF-Bot\node_modules\node-fetch\lib\index.js:1491:11)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'EPROTO',
  code: 'EPROTO'
}

regcmd.js executed successfully.
Executing index.js...
index.js error: (node:5428) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
[30 17:22:43] | [ASF Bot] I am Booting...!
index.js error: Fetch error: FetchError: request to https://127.0.0.1:1242/HealthCheck failed, reason: write EPROTO 0C0A0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:c:\ws\deps\openssl\openssl\ssl\record\ssl3_record.c:355:

    at ClientRequest.<anonymous> (C:\Users\Brooklin\Documents\GitHub\ASF-Bot\node_modules\node-fetch\lib\index.js:1491:11)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'EPROTO',
  code: 'EPROTO'
}
```

**Comment by ManiacMinor** [comment]
It looks like my issue is HTTPS?

https://127.0.0.1:1242/Api/Bot/ASF throws an error but http://127.0.0.1:1242/Api/Bot/ASF does not.

Is there a way I can resolve this?

**Comment by zerox003** [comment]
first of all I'd recommend cloning my fork since I only send a merge request after some bigger updates. 
second I might make it easier to switch between http and https but for now you'd need to go into `index.js` AND `regcmd.js` and change https to http. 
I'll push later today an update to my branch making it more user friendly

**Comment by ManiacMinor** [comment]
The issue is fixed in zerox003's branch. Thanks for this.
